<a href="https://colab.research.google.com/github/zebsoftware/Machine-Learning/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
country = ["pakistan",'india','nepal']
pd.Series(country)

0    pakistan
1       india
2       nepal
dtype: object

In [ ]:
marks =[31,45,87,78]
pd.Series(marks)

0    31
1    45
2    87
3    78
dtype: int64

In [ ]:
subjects = ['maths','english', 'physics','urdu']
pd.Series(marks,index=subjects)
print(marks)

[31, 45, 87, 78]

In [ ]:
pd.Series(marks,index=subjects,name="my marks")
marks_series=pd.Series(marks,index=subjects,name="my marks")

In [ ]:
marks_dict={
    'maths':31,
    'english':45,
    'physics':87,
    'urdu':78
}
marks_dict = pd.Series(marks_dict,name="ANWAR MARKS")

In [ ]:
marks = pd.Series(marks)
marks.size

4

In [ ]:
marks.dtype

dtype('int64')

In [ ]:
marks_dict.name

'ANWAR MARKS'

In [ ]:
marks.is_unique

True

In [ ]:
marks.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
marks_series.values

array([31, 45, 87, 78])

In [24]:
from numpy._core.fromnumeric import squeeze
import pandas as pd
import numpy as np
type(pd.read_csv('/content/ember_features.csv').squeeze("columns"))


series=pd.read_csv('/content/ember_features.csv').squeeze("columns")
series

,size,vsize,imports,exports,has_debug,has_relocations,has_resources,has_signature,has_tls,symbols,...,largest_section_size,entry_is_text,num_dlls,total_imports,suspicious_api_count,num_directories,total_directory_size,import_directory_size,resource_directory_size,label
0,3101705,380928,156,0,0,0,1,0,0,0,...,27648,1,9,156,6,15,29604,200,28672,0
1,504320,524288,619,0,1,0,1,0,0,0,...,455680,1,20,631,4,15,42768,420,38992,0
2,180224,180224,273,0,1,1,1,0,0,53,...,81920,1,6,274,4,15,88648,216,80512,0
3,2377730,77824,8,0,0,0,1,0,1,0,...,36864,0,5,8,0,15,12634,2370,10240,0
4,1153808,1167360,124,0,1,0,1,0,0,0,...,1116672,1,6,124,5,15,1117124,140,1116436,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50107,311296,323584,7,0,0,0,1,0,0,0,...,299008,1,1,15,0,15,5479,40,5343,1
50108,2125824,2936832,1695,18,1,0,1,0,0,0,...,1589248,0,54,2127,1,15,80184,1100,65232,0
50109,722048,722048,11,0,1,1,0,0,0,0,...,483200,1,2,11,0,15,6516,100,0,1
50110,521032,516096,0,1,1,1,1,1,0,0,...,434688,1,0,0,0,15,36253,0,1516,0
50111,2260992,2371584,7,0,0,0,1,0,0,0,...,2252800,1,1,88,0,15,2720,40,2292,0